routes/web.php
<?php

use App\Http\Controllers\ProductsController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', ['uses' => 'ProductsController@index', 'as' => 'index']);

Route::resources(['products' => 'ProductsController']);

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/ProductsController.php
<?php

namespace App\Http\Controllers;

use App\Models\Product;
use http\Exception;
use Illuminate\Http\Request;
use \App\Http\Requests\ProductsRequest;

class ProductsController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @param bool $status
     * @param string $message
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if(\request()->exists("message")){
            $message = \request()->get("message");
        }
        $resources = Product::orderBy('name')->paginate(10);
        return view("index", compact(["resources", "message"]));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view("create");
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param ProductsRequest $request
     * @return \Illuminate\Http\Response
     */
    public function store(ProductsRequest $request)
    {
        $status = true;
        try{

            Product::create($request->all());

        }catch(Exception $e){

            $message = "Falha ao cadastrar produto!";
            return redirect()->route('products.index', compact("message"));

        }
        $message = "Produto cadastrado com sucesso!";
        return redirect()->route('products.index', compact("message"));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $status = true;
        try{

            $resource = Product::findOrFail($id);

        }catch(Exception $e){

            $status = false;
            $message = "Produto não encontrado";
            return redirect()->route('products.index', compact("message"));

        }

        return view("show", compact(["resource"]));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $status = true;
        try{

            $resource = Product::findOrFail($id);

        }catch(Exception $e){

            $status = false;
            $message = "Produto não encontrado";
            return redirect()->route('products.index', compact("message"));

        }

        return view("edit", compact(["resource"]));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param ProductsRequest $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(ProductsRequest $request, $id)
    {
        $status = true;
        try{

            $resource = Product::find($id);
            $resource->update($request->all());

        }catch(Exception $e){

            $status = false;
            $message = "Falha ao atualizar produto!";
            return redirect()->route('products.index', compact("message"));

        }
        $message = "Produto atualizado com sucesso!";
        return redirect()->route('products.index', compact("message"));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $status = true;
        try{

            $resource = Product::find($id);
            $resource->delete();

        }catch(Exception $e){

            $message = "Produto não encontrado";
            return redirect()->route('products.index', compact("message"));

        }
        $message = "Produto excluído com sucesso!";
        return redirect()->route('products.index', compact("message"));
    }
}

resources/views/create.blade.php
@extends('layout')
@section('content')

    <a class="waves-effect waves-light btn-small btn-back right" href="{{route('products.index')}}"><i
                class="material-icons left">chevron_left</i>Voltar</a>
    <h4>Cadastrar Produto</h4>
    <form action="{{route('products.store')}}" method="post">
        {{ csrf_field() }}

        <div class="row">
            <div class="input-field col s12">
                <input name="name" id="name" type="text" class="validate" data-length="255" value="{{ old('name') }}">
                <label for="name">Nome:</label>
                <div id="error-name" class="row error">
                    @if($errors->has('name'))
                        Nome inválido!
                        @endif
                </div>
            </div>
        </div>
        <div class="row">
            <div class="input-field col s6">
                <input name="amount" id="amount" type="text" class="validate" value="{{ old('amount') }}">
                <label for="amount">Preço:</label>
                <div id="error-amount" class="row error">
                    @if($errors->has('amount'))
                        Preço inválido!
                    @endif
                </div>
            </div>
            <div class="input-field col s6">
                <input name="quantity" id="quantity" type="number" min="0" step="1" class="validate" value="{{ old('quantity') }}">
                <label for="quantity">Quantidade em Estoque:</label>
                <div id="error-quantity" class="row error">
                    @if($errors->has('quantity'))
                        Estoque inválido!
                    @endif
                </div>
            </div>
        </div>
        <div class="row">
            <button class="waves-effect waves-light btn-large right" type="submit"><i class="material-icons left">save</i>Salvar</button>
        </div>
    </form>
    {{-- Importa máscara valor monetário --}}
    <script src="{{asset('js/jquery.priceformat.min.js')}}"></script>
    {{-- Máscaras campos formulário --}}
    <script src="{{asset('js/form-mask.js')}}"></script>
    {{-- Validação de envio do formulário --}}
    <script src="{{asset('js/form-validate.js')}}"></script>
@endsection

resources/views/edit.blade.php
@extends('layout')
@section('content')

    <a class="waves-effect waves-light btn-small btn-back right" href="{{route('products.index')}}"><i
                class="material-icons left">chevron_left</i>Voltar</a>
    <h4>Editar - {{$resource->name}}</h4>
    <form action="{{route('products.update', ['id' => $resource->id])}}" method="post">
        {{ csrf_field() }}
        {{ method_field('put') }}

        <div class="row">
            <div class="input-field col s12">
                <input name="name" id="name" value="{{$resource->name}}" type="text" class="validate" data-length="255">
                <label for="name">Nome:</label>
                <div id="error-name" class="row error">
                    @if($errors->has('name'))
                        Nome inválido!
                    @endif
                </div>
            </div>
        </div>
        <div class="row">
            <div class="input-field col s6">
                <input name="amount" id="amount" value="{{$resource->amount}}" type="text" class="validate">
                <label for="amount">Preço:</label>
                <div id="error-amount" class="row error">
                    @if($errors->has('amount'))
                        Preço inválido!
                    @endif
                </div>
            </div>
            <div class="input-field col s6">
                <input name="quantity" id="quantity" value="{{$resource->quantity}}" type="number" min="0" step="1" class="validate">
                <label for="quantity">Quantidade em Estoque:</label>
                <div id="error-quantity" class="row error">
                    @if($errors->has('quantity'))
                        Estoque inválido!
                    @endif
                </div>
            </div>
        </div>
        <div class="row">
            <button class="waves-effect waves-light btn-large right" type="submit"><i class="material-icons left">save</i>Salvar</button>
        </div>
    </form>

    {{-- Importa máscara valor monetário --}}
    <script src="{{asset('js/jquery.priceformat.min.js')}}"></script>
    {{-- Máscaras campos formulário --}}
    <script src="{{asset('js/form-mask.js')}}"></script>
    {{-- Validação de envio do formulário --}}
    <script src="{{asset('js/form-validate.js')}}"></script>
@endsection

resources/views/index.blade.php
@extends('layout')
@section('content')

    <a class="waves-effect waves-light btn-large right" href="{{route('products.create')}}"><i class="material-icons left">add_box</i>Cadastrar</a>
    <h4>Produtos</h4>
    <table class="highlight">
        <thead>
        <tr>
            <th>Nome</th>
            <th>Preço</th>
            <th>Quantidade em Estoque</th>
            <th>Opções</th>
        </tr>
        </thead>
        <tbody>
            @foreach($resources as $resource)
                <tr>
                    <td>{{$resource->name}}</td>
                    <td>{{"R$" . number_format($resource->amount, 2)}}</td>
                    <td>{{$resource->quantity}}</td>
                    <td>
                        <a href="{{route('products.show', ['id' => $resource->id])}}" class="options"><i class="material-icons" title="Visualizar">info</i></a>
                        <a href="{{route('products.edit', ['id' => $resource->id])}}" class="options"><i class="material-icons" title="Editar">edit</i></a>
                        <form class="form-options" action="{{route('products.destroy', ['id' => $resource->id])}}" method="post">
                            {{csrf_field()}}
                            {{method_field('delete')}}
                            <button type="submit"><i class="material-icons left">delete</i></button>
                        </form>
                        </td>
                </tr>
                @endforeach
        </tbody>
    </table>
    {!! $resources->links('vendor.pagination.default') !!}
@endsection

resources/views/layout.blade.php
<html>
<head>
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="{{asset('css/materialize.min.css')}}"/>

    <!-- Icons Materialize -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <!-- Styles -->
    <link href="{{asset('css/styles.css')}}" rel="stylesheet">

    <!-- Compiled and minified JavaScript Materialize -->
    <script src="{{asset('js/materialize.min.js')}}"></script>

    <!-- Compiled and minified JavaScript JQuery -->
    <script src="{{asset('js/jquery.min.js')}}"></script>

    @if(!empty($message))
        <span id="message">{{$message}}</span>
        <script src="{{asset('js/toast.js')}}"></script>
        @endif

    <title>INDEX - Teste Vinicius S Pereira</title>
</head>
<body>
<nav>
    <div class="nav-wrapper">
        <a href="{{route('products.index')}}" class="brand-logo center">VTest</a>
    </div>
</nav>
<ul id="slide-out" class="sidenav sidenav-fixed">
    <li id="top-nav"><span id="menu-text">Menu</span></li>
    <li><a href="{{route('products.index')}}">Produtos</a></li>
</ul>
<a href="#" data-target="slide-out" class="sidenav-trigger"><i class="material-icons">menu</i></a>

<main>
    <div>
        <div class="row">
            <div class="col s12 m12 l12 xl12">
                <div class="card-panel">
                    @yield('content')
                </div>
            </div>
        </div>
    </div>
</main>
</body>
<footer>

</footer>
</html>

resources/views/show.blade.php
@extends('layout')
@section('content')

    <a class="waves-effect waves-light btn-small btn-back right" href="{{route('products.index')}}"><i class="material-icons left">chevron_left</i>Voltar</a>
    <h4>{{$resource->name}}</h4>
    <div class="row">
        <div class="input-field col s12">
            <input disabled value="{{$resource->name}}" id="disabled" type="text" class="validate">
            <label for="disabled">Nome:</label>
        </div>
    </div>
    <div class="row">
        <div class="input-field col s6">
            <input disabled value="{{$resource->amount}}" id="disabled" type="text" class="validate">
            <label for="disabled">Preço:</label>
        </div>
        <div class="input-field col s6">
            <input disabled value="{{$resource->quantity}}" id="disabled" type="text" class="validate">
            <label for="disabled">Quantidade em Estoque:</label>
        </div>
    </div>
@endsection